return {
PlaceObj('ModItemCode', {
	'name', "5.45x39 Ammo",
	'comment', "adds Caliber 5.45x39",
	'CodeFileName', "Code/5.45x39 Ammo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "556 AMMO",
	'comment', "All 556 Ammo changes",
	'CodeFileName', "Code/556 AMMO.lua",
}),
PlaceObj('ModItemCode', {
	'name', "7.62x54R Ammo",
	'comment', "adds Caliber 7.62x54R",
	'CodeFileName', "Code/7.62x54R Ammo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "762 WP Ammo",
	'comment', "All 762WP Ammo changes",
	'CodeFileName', "Code/762 WP Ammo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "762NATO Ammo",
	'comment', "all 762 Nato ammo changes",
	'CodeFileName', "Code/762NATO Ammo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "9mm AMMO",
	'comment', "All 9mm Ammo changes",
	'CodeFileName', "Code/9mm AMMO.lua",
}),
PlaceObj('ModItemCode', {
	'name', "AllAmmoCausesBleeding",
	'comment', "All ammo causes bleeding",
	'CodeFileName', "Code/AllAmmoCausesBleeding.lua",
}),
PlaceObj('ModItemCode', {
	'name', "CTHCalc",
	'CodeFileName', "Code/CTHCalc.lua",
}),
PlaceObj('ModItemCode', {
	'name', "ChanceToHit",
	'comment', "Updated CTH calculation",
	'CodeFileName', "Code/ChanceToHit.lua",
}),
PlaceObj('ModItemCode', {
	'name', "ClassDef-Inventory",
	'CodeFileName', "Code/ClassDef-Inventory.lua",
}),
PlaceObj('ModItemCode', {
	'name', "DamageCalculation",
	'comment', "Updated damage calculation",
	'CodeFileName', "Code/DamageCalculation.lua",
}),
PlaceObj('ModItemCode', {
	'name', "GetAttackAPCost",
	'comment', "Updated AP cost calculation",
	'CodeFileName', "Code/GetAttackAPCost.lua",
}),
PlaceObj('ModItemCode', {
	'name', "InventoryRolloverInfo",
	'comment', "Show Ready AP",
	'CodeFileName', "Code/InventoryRolloverInfo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "MaxActionPoints",
	'comment', "Increased Max AP for mercs",
	'CodeFileName', "Code/MaxActionPoints.lua",
}),
PlaceObj('ModItemCode', {
	'name', "RolloverInventoryWeaponBase",
	'CodeFileName', "Code/RolloverInventoryWeaponBase.lua",
}),
PlaceObj('ModItemCode', {
	'name', "CombatActionGrenade",
	'CodeFileName', "Code/CombatActionGrenade.lua",
}),
PlaceObj('ModItemGameRuleDef', {
	display_name = T(754966679644, --[[ModItemGameRuleDef APReductionOnHit display_name]] "APReductionOnHit"),
	id = "APReductionOnHit",
	msg_reactions = {
		PlaceObj('MsgReaction', {
			Event = "DamageTaken",
			Handler = function (self, attacker, target, dmg, hit_descr)
				ap_penalty = 1
				if target:GetStatusEffect("SpentAP") then
					ap_penalty = target:GetEffectValue("spent_ap") +1
				else target:AddStatusEffect("SpentAP") 
				end
				target:SetEffectValue("spent_ap", ap_penalty)
				print('Damage: '..tostring(dmg )..'dmg')
				print('AP Penalty: '..tostring(ap_penalty )..'AP')
			end,
			HandlerCode = function (self, attacker, target, dmg, hit_descr)
				ap_penalty = 1
				if target:GetStatusEffect("SpentAP") then
					ap_penalty = target:GetEffectValue("spent_ap") +1
				else target:AddStatusEffect("SpentAP") 
				end
				target:SetEffectValue("spent_ap", ap_penalty)
				print('Damage: '..tostring(dmg )..'dmg')
				print('AP Penalty: '..tostring(ap_penalty )..'AP')
			end,
			param_bindings = false,
		}),
	},
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "AK47",
	'object_class', "AssaultRifle",
	'RepairCost', 20,
	'Reliability', 95,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/AK47",
	'DisplayName', T(230834578565, --[[ModItemInventoryItemCompositeDef AK47 DisplayName]] "AK-47"),
	'DisplayNamePlural', T(821815857686, --[[ModItemInventoryItemCompositeDef AK47 DisplayNamePlural]] "AK-47s"),
	'Description', T(395455981724, --[[ModItemInventoryItemCompositeDef AK47 Description]] "You should not be surprised to find an AK-47 anywhere there is conflict around the world. Simple to use, reliable and dirt cheap. Over 75 million are in circulation worldwide."),
	'AdditionalHint', T(366922187857, --[[ModItemInventoryItemCompositeDef AK47 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Slower Condition loss"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 800,
	'Caliber', "762WP",
	'Damage', 25,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'WeaponRange', 24,
	'DamageFalloff', 90,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_AK47",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Grenadelauncher",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"AK47_Launcher",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"AK47_VerticalGrip",
				"AK47_Handguard_basic",
			},
			'DefaultComponent', "AK47_Handguard_basic",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 6000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "AUG",
	'object_class', "AssaultRifle",
	'Reliability', 85,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/AUG",
	'DisplayName', T(401772190072, --[[ModItemInventoryItemCompositeDef AUG DisplayName]] "AUG"),
	'DisplayNamePlural', T(170072516633, --[[ModItemInventoryItemCompositeDef AUG DisplayNamePlural]] "AUGs"),
	'Description', T(355260974257, --[[ModItemInventoryItemCompositeDef AUG Description]] "A bullpup with heavy use of polymer and one of the first to feature integrated optics. Embodying the concept of switching from heavy main battle rifles to assault rifles with the lighter 5.56 NATO cartridge."),
	'AdditionalHint', T(873640390952, --[[ModItemInventoryItemCompositeDef AUG AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Longer range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 2500,
	'Caliber', "556",
	'Damage', 18,
	'AimAccuracy', 6,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'WeaponRange', 30,
	'DamageFalloff', 75,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_Steyr",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelShort_AUG",
				"BarrelShortImproved_AUG",
				"BarrelLong_AUG",
				"BarrelLongImproved_AUG",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"AUGCompensator_01",
				"AUGCompensator_03",
				"Suppressor",
			},
			'DefaultComponent', "AUGCompensator_01",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"VerticalGrip",
			},
			'DefaultComponent', "VerticalGrip",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Grenadelauncher",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher_AUG",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge",
				"MagNormal",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Mount",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"AUGMount",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"LROptics",
				"LROpticsAdvanced",
				"ThermalScope",
				"ReflexSight",
				"ScopeCOG",
				"AUGScope_Default",
			},
			'DefaultComponent', "AUGScope_Default",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "AR15",
	'object_class', "AssaultRifle",
	'Reliability', 80,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/AR15",
	'DisplayName', T(771409473419, --[[ModItemInventoryItemCompositeDef AR15 DisplayName]] "AR-15"),
	'DisplayNamePlural', T(890786096698, --[[ModItemInventoryItemCompositeDef AR15 DisplayNamePlural]] "AR-15s"),
	'Description', T(429127538220, --[[ModItemInventoryItemCompositeDef AR15 Description]] "Created to ensure the highest constitutional rights of self-defense and the possibility to bear a weapon that's easy as hell to convert to a fully-automatic one because a law-abiding citizen always needs one."),
	'AdditionalHint', T(442842467536, --[[ModItemInventoryItemCompositeDef AR15 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Highly modifiable\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No Auto firing mode with standard Stock"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1800,
	'Caliber', "556",
	'Damage', 18,
	'AimAccuracy', 4,
	'CritChanceScaled', 30,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'WeaponRange', 24,
	'DamageFalloff', 75,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_AR15",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"ScopeCOG",
				"LROptics",
				"LROpticsAdvanced",
				"ThermalScope",
				"ReflexSight",
				"DefaultIronsight_AR15",
				"ImprovedIronsight_AR15",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
				"BarrelLong",
				"BarrelLongImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy_AR_BurstOnly",
				"StockLight_AR_BurstOnly",
				"StockBump",
			},
			'DefaultComponent', "StockHeavy_AR_BurstOnly",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher",
				"VerticalGrip",
				"TacGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"ImprovisedSuppressor",
				"Suppressor",
				"MuzzleBooster",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "AK74",
	'object_class', "AssaultRifle",
	'RepairCost', 20,
	'Reliability', 95,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/AK74",
	'DisplayName', T(208174215994, --[[ModItemInventoryItemCompositeDef AK74 DisplayName]] "AK-74"),
	'DisplayNamePlural', T(496595060055, --[[ModItemInventoryItemCompositeDef AK74 DisplayNamePlural]] "AK-74s"),
	'Description', T(763639428001, --[[ModItemInventoryItemCompositeDef AK74 Description]] "The Soviets revisited their emblematic design around 1974 and this beauty was born. It has sprouted many variations but keeps the long stroke gas piston system of the original design."),
	'AdditionalHint', T(640471499574, --[[ModItemInventoryItemCompositeDef AK74 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Slower Condition loss"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 4000,
	'Caliber', "762WP",
	'Damage', 27,
	'MagazineSize', 30,
	'PenetrationClass', 3,
	'WeaponRange', 24,
	'DamageFalloff', 90,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_AK74",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockLight",
			},
			'DefaultComponent', "StockHeavy",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
				"MagQuick",
			},
			'DefaultComponent', "MagNormalFine",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"ImprovisedSuppressor",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher",
				"Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 6000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "FAMAS",
	'object_class', "AssaultRifle",
	'Reliability', 70,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/FAMAS",
	'DisplayName', T(333458128489, --[[ModItemInventoryItemCompositeDef FAMAS DisplayName]] "FAMAS"),
	'DisplayNamePlural', T(935220508808, --[[ModItemInventoryItemCompositeDef FAMAS DisplayNamePlural]] "FAMAS's"),
	'Description', T(128441867775, --[[ModItemInventoryItemCompositeDef FAMAS Description]] "Bullpup design with utility and ergonomics in mind. The magazines were designed to be single-use and disposable. But no design survives contact with reality - soldiers started reusing them and running into all sorts of problems. A durable mag was later introduced. "),
	'AdditionalHint', T(228920409279, --[[ModItemInventoryItemCompositeDef FAMAS AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased Reload cost\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Less noisy"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 800,
	'Caliber', "556",
	'Damage', 18,
	'AimAccuracy', 4,
	'MagazineSize', 25,
	'PenetrationClass', 2,
	'WeaponRange', 24,
	'DamageFalloff', 75,
	'OverwatchAngle', 1440,
	'Noise', 10,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_FAMAS",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"VerticalGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOGQuick",
				"ScopeCOG",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Compensator",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 4000,
	'ReadyAP', 1000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "FNFAL",
	'object_class', "AssaultRifle",
	'Reliability', 50,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/FNFAL",
	'DisplayName', T(646905657869, --[[ModItemInventoryItemCompositeDef FNFAL DisplayName]] "FN-FAL"),
	'DisplayNamePlural', T(880862197330, --[[ModItemInventoryItemCompositeDef FNFAL DisplayNamePlural]] "FN-FALs"),
	'Description', T(351780337475, --[[ModItemInventoryItemCompositeDef FNFAL Description]] "Often described as the Right Arm of the Free World, it delivers pure Democracy in volleys!"),
	'AdditionalHint', T(164481867278, --[[ModItemInventoryItemCompositeDef FNFAL AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Faster Condition loss"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 1800,
	'Caliber', "762NATO",
	'Damage', 27,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'WeaponRange', 24,
	'DamageFalloff', 90,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_FNFAL",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"FNFAL_Handguard",
			},
			'DefaultComponent', "FNFAL_Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ScopeCOG",
				"ScopeCOGQuick",
				"LROptics",
				"ThermalScope",
				"ReflexSight",
				"ReflexSightAdvanced",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
				"MuzzleBooster",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelHeavy",
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelShort",
				"BarrelShortImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge",
				"MagLargeFine",
				"MagNormal",
				"MagNormalFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockHeavy",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher",
				"TacGrip",
				"VerticalGrip",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 6000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "G36",
	'object_class', "AssaultRifle",
	'Reliability', 90,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/G36",
	'DisplayName', T(716078029900, --[[ModItemInventoryItemCompositeDef G36 DisplayName]] "G36"),
	'DisplayNamePlural', T(929788490033, --[[ModItemInventoryItemCompositeDef G36 DisplayNamePlural]] "G36s"),
	'Description', T(458725729247, --[[ModItemInventoryItemCompositeDef G36 Description]] "Futuristic assault rifle with an integrated dual combat sighting system. The 5.56 NATO cartridge combined with the short-stroke gas piston system make this a joy to shoot."),
	'AdditionalHint', T(962904055566, --[[ModItemInventoryItemCompositeDef G36 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Longer range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 4000,
	'Caliber', "556",
	'Damage', 18,
	'AimAccuracy', 6,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'WeaponRange', 30,
	'DamageFalloff', 60,
	'PointBlankRange', true,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_HKG36",
	'fxClass', "G36",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelLong",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"ScopeCOG",
				"LROptics",
				"ThermalScope",
				"ReflexSightAdvanced",
			},
			'DefaultComponent', "ScopeCOG",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Compensator",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"TacGrip",
				"VerticalGrip",
				"GrenadeLauncher",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockFolded",
				"StockHeavy",
			},
			'DefaultComponent', "StockNormal",
		}),
	},
	'Color', "Black",
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 1000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "Galil",
	'object_class', "AssaultRifle",
	'RepairCost', 50,
	'Reliability', 77,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/Galil",
	'DisplayName', T(770849733453, --[[ModItemInventoryItemCompositeDef Galil DisplayName]] "Galil"),
	'DisplayNamePlural', T(247086775653, --[[ModItemInventoryItemCompositeDef Galil DisplayNamePlural]] "Galils"),
	'Description', T(537768181789, --[[ModItemInventoryItemCompositeDef Galil Description]] "Designed with a bottle opener so the soldiers don't damage the mags while using the gun to open bottles. Tries to emulate the AK-47 for some reason. "),
	'AdditionalHint', T(489035933560, --[[ModItemInventoryItemCompositeDef Galil AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Longer range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> In-built bottle opener"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 2500,
	'Caliber', "762NATO",
	'Damage', 27,
	'CritChanceScaled', 30,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'WeaponRange', 30,
	'DamageFalloff', 90,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_Galil",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelNormal",
				"BarrelShort",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockLight",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Galil_Brake_Default",
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Galil_Brake_Default",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"GrenadeLauncher_Galil",
				"Galil_Handguard_Default",
				"Bipod_Galil",
			},
			'DefaultComponent', "Bipod_Galil",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ThermalScope",
				"ScopeCOG",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge",
				"MagNormal",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 6000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "M14SAW",
	'object_class', "AssaultRifle",
	'Reliability', 80,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/M14",
	'DisplayName', T(744119439231, --[[ModItemInventoryItemCompositeDef M14SAW DisplayName]] "M-14"),
	'DisplayNamePlural', T(150959944620, --[[ModItemInventoryItemCompositeDef M14SAW DisplayNamePlural]] "M-14s"),
	'Description', T(123461829595, --[[ModItemInventoryItemCompositeDef M14SAW Description]] "Take a Garand rifle, then make it heavier and capable of firing full auto. Simply put, it's a Frankenstein monster."),
	'AdditionalHint', T(656272333266, --[[ModItemInventoryItemCompositeDef M14SAW AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1200,
	'Caliber', "762NATO",
	'Damage', 27,
	'AimAccuracy', 5,
	'MagazineSize', 20,
	'PenetrationClass', 2,
	'WeaponRange', 24,
	'DamageFalloff', 90,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_M14",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelHeavy",
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge",
				"MagLargeFine",
				"MagNormal",
				"MagNormalFine",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher_M14",
				"TacGrip_M14",
				"VerticalGrip_M14",
				"Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"M14_Default_Muzzle",
				"Compensator",
				"ImprovisedSuppressor",
				"Suppressor",
				"MuzzleBooster",
			},
			'DefaultComponent', "M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LaserDot",
				"FlashlightDot",
				"UVDot",
				"Flashlight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 6000,
	'ReloadAP', 3000,
	'ReadyAP', 3000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Assault",
	'Id', "M16A2",
	'object_class', "AssaultRifle",
	'Reliability', 80,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/M16A2",
	'DisplayName', T(946995201114, --[[ModItemInventoryItemCompositeDef M16A2 DisplayName]] "M16A2"),
	'DisplayNamePlural', T(232891991009, --[[ModItemInventoryItemCompositeDef M16A2 DisplayNamePlural]] "M16A2s"),
	'Description', T(194595427681, --[[ModItemInventoryItemCompositeDef M16A2 Description]] "The most iconic firearm of the western world, the M16 introduced the 5.56 NATO cartridge which was made for its 20 inch barrel. It's higher bullet velocity improves accuracy at long range and auto-fire handling, though it has less stopping power than its main rival - the AK-47. Don't ask about the forward assist..."),
	'AdditionalHint', T(753223429783, --[[ModItemInventoryItemCompositeDef M16A2 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No Auto firing mode with standard Stock"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1200,
	'Caliber', "556",
	'Damage', 18,
	'AimAccuracy', 6,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'WeaponRange', 24,
	'DamageFalloff', 75,
	'OverwatchAngle', 1440,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_M16A2",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"M16_Handguard",
			},
			'DefaultComponent', "M16_Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ScopeCOG",
				"ScopeCOGQuick",
				"LROptics",
				"ThermalScope",
				"ReflexSight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Compensator",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge",
				"MagNormal",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher_M16A1",
				"VerticalGrip_M16",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Rifle",
	'Id', "Gewehr98",
	'object_class', "SniperRifle",
	'Reliability', 25,
	'ScrapParts', 8,
	'Icon', "UI/Icons/Weapons/Gewehr98",
	'DisplayName', T(136989751826, --[[ModItemInventoryItemCompositeDef Gewehr98 DisplayName]] "Gewehr 98"),
	'DisplayNamePlural', T(171595257376, --[[ModItemInventoryItemCompositeDef Gewehr98 DisplayNamePlural]] "Gewehr 98s"),
	'Description', T(886179819584, --[[ModItemInventoryItemCompositeDef Gewehr98 Description]] "It is said that this Mauser design is the grandpa of all bolt action rifles. Even the modern hunting or military sniper rifles started here. "),
	'AdditionalHint', T(165416275520, --[[ModItemInventoryItemCompositeDef Gewehr98 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Shorter range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very noisy"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1250,
	'Caliber', "762NATO",
	'Damage', 27,
	'AimAccuracy', 5,
	'MagazineSize', 5,
	'PenetrationClass', 2,
	'WeaponRange', 32,
	'DamageFalloff', 90,
	'OverwatchAngle', 360,
	'Noise', 30,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_Gewehr98",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOG",
				"GewehrDefaultSight",
				"ImprovedIronsight",
				"ReflexSightAdvanced",
				"ScopeCOGQuick",
				"ThermalScope",
			},
			'DefaultComponent', "GewehrDefaultSight",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'ModifyRightHandGrip', true,
	'PreparedAttackType', "Both",
	'AvailableAttacks', {
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 8000,
	'ReloadAP', 3000,
	'ReadyAP', 3000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Rifle",
	'Id', "BarretM82",
	'object_class', "SniperRifle",
	'Reliability', 10,
	'ScrapParts', 16,
	'Icon', "UI/Icons/Weapons/M82",
	'DisplayName', T(283248562661, --[[ModItemInventoryItemCompositeDef BarretM82 DisplayName]] "M82"),
	'DisplayNamePlural', T(807786095398, --[[ModItemInventoryItemCompositeDef BarretM82 DisplayNamePlural]] "M82s"),
	'Description', T(570451445918, --[[ModItemInventoryItemCompositeDef BarretM82 Description]] 'The .50 BMG is a heavy machine gun cartridge - hence the name. But place it in a semi auto long range gun and you have a great anti-materiel rifle. Or "shoot through walls" gun. It does need a muzzle break the size of a small shovel to counteract that recoil however. '),
	'AdditionalHint', T(306968985819, --[[ModItemInventoryItemCompositeDef BarretM82 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very high damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High attack costs\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very noisy\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)"),
	'LargeItem', true,
	'Cumbersome', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 9000,
	'Caliber', "50BMG",
	'Damage', 60,
	'AimAccuracy', 5,
	'CritChanceScaled', 20,
	'MagazineSize', 5,
	'PenetrationClass', 3,
	'WeaponRange', 40,
	'DamageFalloff', 90,
	'OverwatchAngle', 360,
	'Noise', 30,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_BarrettM82",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
				"LROpticsAdvanced",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Both",
	'AvailableAttacks', {
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 10000,
	'ReloadAP', 3000,
	'ReadyAP', 4000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Rifle",
	'Id', "DragunovSVD",
	'object_class', "SniperRifle",
	'Reliability', 50,
	'ScrapParts', 14,
	'Icon', "UI/Icons/Weapons/Dragunov",
	'DisplayName', T(994514084146, --[[ModItemInventoryItemCompositeDef DragunovSVD DisplayName]] "Dragunov"),
	'DisplayNamePlural', T(540133151566, --[[ModItemInventoryItemCompositeDef DragunovSVD DisplayNamePlural]] "Dragunovs"),
	'Description', T(513373787384, --[[ModItemInventoryItemCompositeDef DragunovSVD Description]] "Not what it seems at first glance. On the outside it looks like an AK but actually uses a short stroke gas piston system that reduces the recoil and allows for better follow up shots. It is more of a close support designated marksman's rifle than a sniper one. "),
	'AdditionalHint', T(954497306670, --[[ModItemInventoryItemCompositeDef DragunovSVD AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Decreased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very noisy\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Rifle with Burst firing mode"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1750,
	'Caliber', "762WP",
	'Damage', 27,
	'AimAccuracy', 3,
	'CritChance', 10,
	'CritChanceScaled', 0,
	'MagazineSize', 10,
	'PenetrationClass', 2,
	'WeaponRange', 36,
	'DamageFalloff', 90,
	'OverwatchAngle', 360,
	'Noise', 30,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_Dragunov",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockLight",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"LROptics_DragunovDefault",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
				"LROpticsAdvanced",
				"ReflexSightAdvanced",
				"ScopeCOGQuick",
			},
			'DefaultComponent', "LROptics_DragunovDefault",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Both",
	'AvailableAttacks', {
		"SingleShot",
		"BurstFire",
		"CancelShot",
	},
	'ShootAP', 8000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Rifle",
	'Id', "M24Sniper",
	'object_class', "SniperRifle",
	'Reliability', 44,
	'ScrapParts', 14,
	'Icon', "UI/Icons/Weapons/M24",
	'DisplayName', T(990874644603, --[[ModItemInventoryItemCompositeDef M24Sniper DisplayName]] "M24"),
	'DisplayNamePlural', T(934741885494, --[[ModItemInventoryItemCompositeDef M24Sniper DisplayNamePlural]] "M24s"),
	'Description', T(176267840640, --[[ModItemInventoryItemCompositeDef M24Sniper Description]] "US Army sniper weapon system that replaced the M21 (based on the M14). Apparently semi-auto was still not up to par with what snipers needed in terms of reliability and accuracy that bolt action can provide. "),
	'AdditionalHint', T(393220213742, --[[ModItemInventoryItemCompositeDef M24Sniper AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very noisy"),
	'LargeItem', true,
	'Cumbersome', true,
	'UnitStat', "Marksmanship",
	'Cost', 2500,
	'Caliber', "762NATO",
	'Damage', 27,
	'AimAccuracy', 5,
	'MagazineSize', 5,
	'PenetrationClass', 2,
	'WeaponRange', 36,
	'DamageFalloff', 90,
	'OverwatchAngle', 360,
	'Noise', 30,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_M24",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockLight",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
			},
			'DefaultComponent', "LROptics",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Both",
	'AvailableAttacks', {
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 8000,
	'ReloadAP', 3000,
	'ReadyAP', 4000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Rifle",
	'Id', "PSG1",
	'object_class', "SniperRifle",
	'Reliability', 53,
	'ScrapParts', 14,
	'Icon', "UI/Icons/Weapons/PSG1",
	'DisplayName', T(470341245109, --[[ModItemInventoryItemCompositeDef PSG1 DisplayName]] "PSG1"),
	'DisplayNamePlural', T(621291356192, --[[ModItemInventoryItemCompositeDef PSG1 DisplayNamePlural]] "PSG1s"),
	'Description', T(197338573054, --[[ModItemInventoryItemCompositeDef PSG1 Description]] 'Semi-auto precision rifle initially designed for law enforcement after the 1972 Munich Olympics. They skipped adding any iron sights and went straight to a scope. Adjustable buttstock, cheekpiece, trigger unit, and much more. This gun screams "I can watch this hostage situation all day as I wait for the greenlight". '),
	'AdditionalHint', T(449269460325, --[[ModItemInventoryItemCompositeDef PSG1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 3200,
	'Caliber', "762NATO",
	'Damage', 27,
	'AimAccuracy', 5,
	'CritChanceScaled', 30,
	'MagazineSize', 5,
	'PenetrationClass', 2,
	'WeaponRange', 36,
	'DamageFalloff', 90,
	'OverwatchAngle', 360,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_PSG1",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockHeavy",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"PSG_DefaultScope",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
			'DefaultComponent', "PSG_DefaultScope",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"FlashlightDot_PSG_M1",
				"Flashlight_PSG_M1",
				"LaserDot_PSG_M1",
				"UVDot_PSG_M1",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Both",
	'AvailableAttacks', {
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 8000,
	'ReloadAP', 2000,
	'ReadyAP', 4000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Rifle",
	'Id', "Winchester1894",
	'object_class', "SniperRifle",
	'Reliability', 95,
	'ScrapParts', 8,
	'Icon', "UI/Icons/Weapons/Winchester",
	'DisplayName', T(442994509907, --[[ModItemInventoryItemCompositeDef Winchester1894 DisplayName]] "Winchester 1894"),
	'DisplayNamePlural', T(641965668737, --[[ModItemInventoryItemCompositeDef Winchester1894 DisplayNamePlural]] "Winchester 1894s"),
	'Description', T(842544105162, --[[ModItemInventoryItemCompositeDef Winchester1894 Description]] 'One of the guns that "won the West". The magazine tube holds more ammo than your standard bolt action rifle. How this one got in this part of the world is anyone\'s guess.'),
	'AdditionalHint', T(419344807969, --[[ModItemInventoryItemCompositeDef Winchester1894 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Shorter range"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1250,
	'Caliber', "44CAL",
	'Damage', 25,
	'AimAccuracy', 5,
	'CritChanceScaled', 20,
	'MagazineSize', 9,
	'WeaponRange', 24,
	'DamageFalloff', 90,
	'OverwatchAngle', 360,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_Winchester",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelNormal",
				"BarrelShort_Winchester",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'ModifyRightHandGrip', true,
	'PreparedAttackType', "Both",
	'AvailableAttacks', {
		"SingleShot",
		"CancelShot",
	},
	'ShootAP', 7000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - MG",
	'Id', "BrowningM2HMG",
	'object_class', "MachineGun",
	'Reliability', 80,
	'ScrapParts', 20,
	'Icon', "UI/Icons/Weapons/M2Browning",
	'DisplayName', T(748949216353, --[[ModItemInventoryItemCompositeDef BrowningM2HMG DisplayName]] "M2 Browning"),
	'DisplayNamePlural', T(677109638447, --[[ModItemInventoryItemCompositeDef BrowningM2HMG DisplayNamePlural]] "M2 Brownings"),
	'Description', T(402244888892, --[[ModItemInventoryItemCompositeDef BrowningM2HMG Description]] "When you're a dime short of buying some tank ordnance but you won't make a compromise with power."),
	'AdditionalHint', T(825906626200, --[[ModItemInventoryItemCompositeDef BrowningM2HMG AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Stationary weapon\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very high damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very noisy"),
	'LargeItem', true,
	'Cumbersome', true,
	'UnitStat', "Marksmanship",
	'Cost', 4200,
	'Caliber', "50BMG",
	'Damage', 40,
	'MagazineSize', 100,
	'PenetrationClass', 3,
	'WeaponRange', 30,
	'DamageFalloff', 90,
	'OverwatchAngle', 3600,
	'Noise', 30,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_M2Browning",
	'ComponentSlots', {},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Machine Gun",
	'AvailableAttacks', {
		"MGBurstFire",
	},
	'ShootAP', 4000,
	'ReloadAP', 6000,
	'ReadyAP', 4000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - MG",
	'Id', "FNMinimi",
	'object_class', "MachineGun",
	'RepairCost', 120,
	'Reliability', 85,
	'ScrapParts', 16,
	'Icon', "UI/Icons/Weapons/Minimi",
	'DisplayName', T(264009668594, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayName]] "Minimi"),
	'DisplayNamePlural', T(290171506083, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayNamePlural]] "Minimis"),
	'Description', T(605177148324, --[[ModItemInventoryItemCompositeDef FNMinimi Description]] "The 5.56 NATO Minimi is meant to provide squad-level fire support. It does so well that it was adopted by the US military and most people know it as the M249 squad automatic weapon. There is also a Minimi variant firing 7.62 NATO rounds."),
	'AdditionalHint', T(929951303187, --[[ModItemInventoryItemCompositeDef FNMinimi AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Wider attack cone\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Reduced armor penetration"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 2750,
	'Caliber', "556",
	'Damage', 18,
	'AimAccuracy', 4,
	'MagazineSize', 100,
	'PenetrationClass', 2,
	'WeaponRange', 30,
	'DamageFalloff', 90,
	'OverwatchAngle', 2700,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_FNMinimi",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"ReflexSight",
				"ReflexSightAdvanced",
				"LROptics",
				"LROpticsAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Machine Gun",
	'AvailableAttacks', {
		"MGBurstFire",
	},
	'ShootAP', 4000,
	'ReloadAP', 5000,
	'ReadyAP', 3000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - MG",
	'Id', "HK21",
	'object_class', "MachineGun",
	'Reliability', 90,
	'ScrapParts', 16,
	'Icon', "UI/Icons/Weapons/HK21",
	'DisplayName', T(878277950457, --[[ModItemInventoryItemCompositeDef HK21 DisplayName]] "HK21"),
	'DisplayNamePlural', T(868927704161, --[[ModItemInventoryItemCompositeDef HK21 DisplayNamePlural]] "HK21s"),
	'Description', T(806289458910, --[[ModItemInventoryItemCompositeDef HK21 Description]] "Combine an assault rifle with a machine gun and you get HK21. Unlike most hybrid guns, it performs each role extremely well."),
	'AdditionalHint', T(370222757863, --[[ModItemInventoryItemCompositeDef HK21 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Less accurate when fired from the hip"),
	'LargeItem', true,
	'Cumbersome', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 3500,
	'Caliber', "762NATO",
	'Damage', 27,
	'AimAccuracy', 6,
	'MagazineSize', 120,
	'PenetrationClass', 2,
	'WeaponRange', 30,
	'DamageFalloff', 90,
	'OverwatchAngle', 1800,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_HK21",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"DefaultMuzzle_HK21",
				"MuzzleBooster",
				"Compensator",
			},
			'DefaultComponent', "DefaultMuzzle_HK21",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"TacGrip",
				"VerticalGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Machine Gun",
	'AvailableAttacks', {
		"MGBurstFire",
	},
	'ShootAP', 4000,
	'ReloadAP', 5000,
	'ReadyAP', 4000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - MG",
	'Id', "MG42",
	'object_class', "MachineGun",
	'Reliability', 95,
	'ScrapParts', 12,
	'Icon', "UI/Icons/Weapons/MG42",
	'DisplayName', T(241499984458, --[[ModItemInventoryItemCompositeDef MG42 DisplayName]] "MG42"),
	'DisplayNamePlural', T(805270982786, --[[ModItemInventoryItemCompositeDef MG42 DisplayNamePlural]] "MG42s"),
	'Description', T(285350798938, --[[ModItemInventoryItemCompositeDef MG42 Description]] "With its incredible rate of fire, the MG42 provides amazing suppression capacity. She might be old but she's German."),
	'AdditionalHint', T(694596170063, --[[ModItemInventoryItemCompositeDef MG42 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Less accurate when fired from the hip"),
	'LargeItem', true,
	'Cumbersome', true,
	'UnitStat', "Marksmanship",
	'Cost', 1200,
	'Caliber', "762NATO",
	'Damage', 27,
	'MagazineSize', 100,
	'PenetrationClass', 2,
	'WeaponRange', 30,
	'DamageFalloff', 90,
	'OverwatchAngle', 1800,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_MG42",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod_MG42",
			},
			'DefaultComponent', "Bipod_MG42",
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Machine Gun",
	'AvailableAttacks', {
		"MGBurstFire",
	},
	'ShootAP', 4000,
	'ReloadAP', 5000,
	'ReadyAP', 4000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - MG",
	'Id', "RPK74",
	'object_class', "MachineGun",
	'Reliability', 95,
	'ScrapParts', 16,
	'Icon', "UI/Icons/Weapons/RPK74",
	'DisplayName', T(743196155284, --[[ModItemInventoryItemCompositeDef RPK74 DisplayName]] "RPK-74"),
	'DisplayNamePlural', T(227440765029, --[[ModItemInventoryItemCompositeDef RPK74 DisplayNamePlural]] "RPK-74s"),
	'Description', T(596731408389, --[[ModItemInventoryItemCompositeDef RPK74 Description]] "Built upon the AK platform with a thicker barrel and other small changes to allow for better sustained fire capability. This general purpose machine gun is meant to be a squad force multiplier with easy operation, integration, and ammo compatibility with other AK weapons."),
	'AdditionalHint', T(299021793130, --[[ModItemInventoryItemCompositeDef RPK74 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Slower Condition loss"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1800,
	'Caliber', "762WP",
	'Damage', 27,
	'MagazineSize', 60,
	'PenetrationClass', 2,
	'WeaponRange', 30,
	'DamageFalloff', 90,
	'OverwatchAngle', 1800,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_RPK74",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagQuick",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"RPK74_Hanguard_Basic",
				"RPK74_VerticalGrip",
			},
			'DefaultComponent', "RPK74_Hanguard_Basic",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
				"LROpticsAdvanced",
				"ScopeCOGQuick",
				"ReflexSightAdvanced",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
	},
	'HolsterSlot', "Shoulder",
	'PreparedAttackType', "Machine Gun",
	'AvailableAttacks', {
		"MGBurstFire",
	},
	'ShootAP', 4000,
	'ReloadAP', 3000,
	'ReadyAP', 3000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - SMG",
	'Id', "AKSU",
	'object_class', "SubmachineGun",
	'RepairCost', 50,
	'Reliability', 80,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/AKSU",
	'DisplayName', T(412741432224, --[[ModItemInventoryItemCompositeDef AKSU DisplayName]] "AK-SU"),
	'DisplayNamePlural', T(327599542895, --[[ModItemInventoryItemCompositeDef AKSU DisplayNamePlural]] "AK-SUs"),
	'Description', T(513801149283, --[[ModItemInventoryItemCompositeDef AKSU Description]] "Short versions of the AK-74 intended for Spec Ops and vehicle crew personal defense. It needed a custom gas block and muzzle booster to work properly. Americans call it Krinkov but Russians have a more intimate nickname - Ksyukha or sometimes Suchka. And yes, there is a thigh holster for it. "),
	'AdditionalHint', T(476903417282, --[[ModItemInventoryItemCompositeDef AKSU AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High damage"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 2250,
	'Caliber', "762WP",
	'Damage', 27,
	'CritChanceScaled', 20,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'PointBlankRange', true,
	'OverwatchAngle', 1440,
	'Noise', 15,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_AKS74U",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"AKSU_Hanguard_Basic",
				"AKSU_VerticalGrip",
			},
			'DefaultComponent', "AKSU_Hanguard_Basic",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagQuick",
				"MagLargeFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "MuzzleBooster",
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 1000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - SMG",
	'Id', "M4Commando",
	'object_class', "SubmachineGun",
	'Reliability', 80,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/Commando",
	'DisplayName', T(276891873032, --[[ModItemInventoryItemCompositeDef M4Commando DisplayName]] "Commando"),
	'DisplayNamePlural', T(638894130925, --[[ModItemInventoryItemCompositeDef M4Commando DisplayNamePlural]] "Commandos"),
	'Description', T(611281542936, --[[ModItemInventoryItemCompositeDef M4Commando Description]] "How would you make a short barrel M16 work? Answer - lower muzzle velocity and huge muzzle flash."),
	'AdditionalHint', T(828327248075, --[[ModItemInventoryItemCompositeDef M4Commando AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 2700,
	'Caliber', "556",
	'Damage', 18,
	'AimAccuracy', 4,
	'CritChanceScaled', 30,
	'MagazineSize', 30,
	'PenetrationClass', 2,
	'PointBlankRange', true,
	'OverwatchAngle', 1440,
	'Noise', 15,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_CAR15",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"Handguard_Commando",
				"VerticalGrip_Commando",
				"GrenadeLauncher_Commando",
			},
			'DefaultComponent', "Handguard_Commando",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
				"ReflexSightAdvanced",
				"ScopeCOGQuick",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 1000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - SMG",
	'Id', "MP5",
	'object_class', "SubmachineGun",
	'Reliability', 85,
	'ScrapParts', 8,
	'Icon', "UI/Icons/Weapons/MP5",
	'DisplayName', T(523395391466, --[[ModItemInventoryItemCompositeDef MP5 DisplayName]] "MP5"),
	'DisplayNamePlural', T(908688120516, --[[ModItemInventoryItemCompositeDef MP5 DisplayNamePlural]] "MP5s"),
	'Description', T(814700471139, --[[ModItemInventoryItemCompositeDef MP5 Description]] "The submachine gun used by most police tactical teams and counter terrorist units. It has seen a lot of action since it was introduced in the sixties, but the 9mm cartridge and the widespread availability of body armor gradually decreased the interest in the MP5. "),
	'AdditionalHint', T(686450423492, --[[ModItemInventoryItemCompositeDef MP5 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Less noisy"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1600,
	'Caliber', "9mm",
	'Damage', 15,
	'AimAccuracy', 6,
	'MagazineSize', 30,
	'PointBlankRange', true,
	'OverwatchAngle', 1440,
	'Noise', 10,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_MP5",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'Modifiable', false,
			'AvailableComponents', {
				"MP5_Handguard",
			},
			'DefaultComponent', "MP5_Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelLong",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockHeavy",
				"StockNo",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 1000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - SMG",
	'Id', "MP5K",
	'object_class', "SubmachineGun",
	'Reliability', 85,
	'ScrapParts', 8,
	'Icon', "UI/Icons/Weapons/MP5K",
	'DisplayName', T(788721675469, --[[ModItemInventoryItemCompositeDef MP5K DisplayName]] "MP5K"),
	'DisplayNamePlural', T(581254870398, --[[ModItemInventoryItemCompositeDef MP5K DisplayNamePlural]] "MP5Ks"),
	'Description', T(712573321715, --[[ModItemInventoryItemCompositeDef MP5K Description]] "Brutally short MP5 designed for close quarters engagements and personal defense. There is even a suitcase with a trigger on the handle for covert escort jobs."),
	'AdditionalHint', T(933490870012, --[[ModItemInventoryItemCompositeDef MP5K AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Less noisy"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1600,
	'Caliber', "9mm",
	'Damage', 15,
	'AimAccuracy', 5,
	'MagazineSize', 30,
	'PointBlankRange', true,
	'OverwatchAngle', 1440,
	'Noise', 10,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_MP5",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"VerticalGrip",
			},
			'DefaultComponent', "VerticalGrip",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelShort",
			},
			'DefaultComponent', "BarrelShort",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockHeavy",
				"StockNo",
			},
			'DefaultComponent', "StockNo",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
		}),
	},
	'HolsterSlot', "Leg",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - SMG",
	'Id', "UZI",
	'object_class', "SubmachineGun",
	'Reliability', 75,
	'ScrapParts', 6,
	'Icon', "UI/Icons/Weapons/UZI",
	'DisplayName', T(187581253321, --[[ModItemInventoryItemCompositeDef UZI DisplayName]] "UZI"),
	'DisplayNamePlural', T(250861566759, --[[ModItemInventoryItemCompositeDef UZI DisplayNamePlural]] "UZIs"),
	'Description', T(687861823166, --[[ModItemInventoryItemCompositeDef UZI Description]] "Designed as a personal defense weapon for rear echelon troops in the Israel Defense Forces. Intended to be used with a buttstock, but regularly wielded one-handed. Can deliver a lot of lead though accuracy may vary. "),
	'AdditionalHint', T(469763537931, --[[ModItemInventoryItemCompositeDef UZI AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Decreased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Less noisy\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Firing Modes: Burst, Auto"),
	'UnitStat', "Marksmanship",
	'Cost', 1200,
	'Caliber', "9mm",
	'Damage', 10,
	'MagazineSize', 30,
	'PointBlankRange', true,
	'OverwatchAngle', 1440,
	'Noise', 10,
	'Entity', "Weapon_Uzi",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelLong",
				"BarrelLongImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
				"MagLargeFine",
				"MagNormalFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ReflexSightAdvanced",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
			},
		}),
	},
	'HolsterSlot', "Leg",
	'AvailableAttacks', {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"DualShot",
		"RunAndGun",
		"CancelShot",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "AA12",
	'object_class', "Shotgun",
	'RepairCost', 50,
	'Reliability', 80,
	'ScrapParts', 12,
	'Icon', "UI/Icons/Weapons/AA12",
	'DisplayName', T(257086606584, --[[ModItemInventoryItemCompositeDef AA12 DisplayName]] "AA12"),
	'DisplayNamePlural', T(444526457634, --[[ModItemInventoryItemCompositeDef AA12 DisplayNamePlural]] "AA12s"),
	'Description', T(763278602120, --[[ModItemInventoryItemCompositeDef AA12 Description]] "Firing from an open bolt, the AA12 has more similarity with some machine guns than with other shotguns. Boasting reduced recoil for a 12-gauge round, it is made for sustained fire."),
	'AdditionalHint', T(568294639430, --[[ModItemInventoryItemCompositeDef AA12 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Decreased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Special firing mode: Buckshot Burst"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 3200,
	'Caliber', "12gauge",
	'Damage', 26,
	'ObjDamageMod', 150,
	'MagazineSize', 15,
	'WeaponRange', 8,
	'PointBlankRange', true,
	'OverwatchAngle', 1200,
	'BuckshotConeAngle', 1200,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_AA12",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelLongShotgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOGQuick",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight_aa12",
				"LaserDot_aa12",
				"FlashlightDot_aa12",
				"UVDot_aa12",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
				"Compensator",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"BuckshotBurst",
		"Buckshot",
		"CancelShotCone",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Shotgun",
	'Id', "Auto5",
	'object_class', "Shotgun",
	'RepairCost', 50,
	'Reliability', 20,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/Browning Auto-5",
	'DisplayName', T(168346986279, --[[ModItemInventoryItemCompositeDef Auto5 DisplayName]] "Auto-5"),
	'DisplayNamePlural', T(616333971173, --[[ModItemInventoryItemCompositeDef Auto5 DisplayNamePlural]] "Auto-5s"),
	'Description', T(953932195235, --[[ModItemInventoryItemCompositeDef Auto5 Description]] "First mass produced semi-automatic shotgun in the world. Turned out it was one hell of a good gun for jungle close-quarter firefights. "),
	'AdditionalHint', T(404519137847, --[[ModItemInventoryItemCompositeDef Auto5 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1200,
	'Caliber', "12gauge",
	'Damage', 26,
	'ObjDamageMod', 150,
	'AimAccuracy', 4,
	'MagazineSize', 5,
	'WeaponRange', 8,
	'PointBlankRange', true,
	'OverwatchAngle', 1200,
	'BuckshotConeAngle', 1200,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_Auto5",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"DuckbillChoke",
				"FullChoke",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"Auto5_Basic_LMag",
				"Auto5_Basic_NMag",
				"Auto5_Long_LMag",
				"Auto5_Long_NMag",
				"Auto5_Short_NMag",
			},
			'DefaultComponent', "Auto5_Basic_NMag",
		}),
	},
	'HolsterSlot', "Shoulder",
	'ModifyRightHandGrip', true,
	'AvailableAttacks', {
		"Buckshot",
		"CancelShotCone",
	},
	'ShootAP', 4000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Shotgun",
	'Id', "DoubleBarrelShotgun",
	'object_class', "Shotgun",
	'RepairCost', 50,
	'Reliability', 50,
	'ScrapParts', 8,
	'Icon', "UI/Icons/Weapons/Double-barrelled Shotgun",
	'DisplayName', T(474486882296, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun DisplayName]] "Double-Barrel"),
	'DisplayNamePlural', T(932176019316, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun DisplayNamePlural]] "Double-Barrels"),
	'Description', T(377948443984, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun Description]] "A simple hunting weapon. Fancier combat shotguns can shoot semi and fully automatic but only the double-barrel can shoot two shells at once. "),
	'AdditionalHint', T(597514970076, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Limited ammo capacity\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Greatly decreased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Special firing mode: Double Barrel"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 700,
	'Caliber', "12gauge",
	'Damage', 28,
	'ObjDamageMod', 150,
	'AimAccuracy', 1,
	'CritChanceScaled', 30,
	'MagazineSize', 2,
	'WeaponRange', 8,
	'PointBlankRange', true,
	'OverwatchAngle', 1200,
	'BuckshotConeAngle', 1200,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_DBShotgun",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLongShotgun",
				"BarrelNormal",
				"BarrelShortShotgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
	},
	'HolsterSlot', "Shoulder",
	'ModifyRightHandGrip', true,
	'AvailableAttacks', {
		"Buckshot",
		"DoubleBarrel",
		"CancelShotCone",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Firearm - Shotgun",
	'Id', "M41",
	'object_class', "Shotgun",
	'RepairCost', 50,
	'Reliability', 71,
	'ScrapParts', 10,
	'Icon', "UI/Icons/Weapons/M1014",
	'DisplayName', T(877213322880, --[[ModItemInventoryItemCompositeDef M41 DisplayName]] "M1014"),
	'DisplayNamePlural', T(950033408144, --[[ModItemInventoryItemCompositeDef M41 DisplayNamePlural]] "M1014s"),
	'Description', T(152360624134, --[[ModItemInventoryItemCompositeDef M41 Description]] "12-gauge semi-auto slick Italian. Boasting little need for maintenance and high level of reliability, it is loved by law enforcement and military alike."),
	'AdditionalHint', T(166500632100, --[[ModItemInventoryItemCompositeDef M41 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Longer range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'LargeItem', true,
	'UnitStat', "Marksmanship",
	'Cost', 1700,
	'Caliber', "12gauge",
	'Damage', 32,
	'ObjDamageMod', 150,
	'AimAccuracy', 5,
	'MagazineSize', 6,
	'WeaponRange', 12,
	'PointBlankRange', true,
	'OverwatchAngle', 1200,
	'BuckshotConeAngle', 1200,
	'HandSlot', "TwoHanded",
	'Entity', "Weapon_Benelli_M4",
	'ComponentSlots', {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelShortShotgun_Benelli",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ScopeCOG",
				"LROptics",
				"ReflexSight",
				"ThermalScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
			},
		}),
	},
	'HolsterSlot', "Shoulder",
	'AvailableAttacks', {
		"Buckshot",
		"CancelShotCone",
	},
	'ShootAP', 5000,
	'ReloadAP', 3000,
	'ReadyAP', 2000,
}),
}
