return PlaceObj('ModDef', {
	'title', "Revised",
	'description', "This mod is designed to create more complete experiencel, reflecting real life combat as much as possible.\nThe design philosophy of the mod: deadlier weapons, lower accuracy.\n\nMajor changes:\n1. Auto damage increased\n2. Accuracy decreased to compensate.\n3. Dexterity used for close-range combat, marksmanship for aiming\n4. Lighting reflexes should not work on stealth kill\n5. Attacking new target requires 1AP for Weapon ready\n6. Pistols are excluded from th 5 rule (should make them slightly better)\n\nThis is ALPHA version of the mod - might be not well balanced. Feedback and suggestions are welcome.",
	'image', "Mod/Db7c5fd/Images/JA3Revised 2.png",
	'last_changes', "Initial commit",
	'id', "Db7c5fd",
	'content_path', "Mod/Db7c5fd/",
	'author', "Ablomis",
	'version_minor', 1,
	'version', 679,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/CTHCalc.lua",
		"Code/ChanceToHit.lua",
		"Code/DamageCalculation.lua",
		"Code/FirearmProperty.lua",
		"Code/GetAttackAPCost.lua",
		"InventoryItem/AK47.lua",
	},
	'saved', 1690141235,
	'code_hash', 7818093239788046865,
	'steam_id', "3008768068",
})