return PlaceObj('ModDef', {
	'title', "Revised",
	'description', "This mod is designed to create more complete experiencel, reflecting real life combat as much as possible.\nThe design philosophy of the mod: deadlier weapons, lower accuracy.\n\nMajor changes:\n1. Auto damage increased\n2. Accuracy decreased to compensate.\n3. Dexterity used for close-range combat, marksmanship for aiming\n4. Lighting reflexes should not work on stealth kill\n5. Each weapon now has AP ready\n6. Increased number of AP for mercs to compensate\n\nThis is ALPHA version of the mod - might be not well balanced. Feedback and suggestions are welcome.",
	'image', "Mod/Db7c5fd/Images/JA3Revised 2.png",
	'last_changes', "Initial commit",
	'id', "Db7c5fd",
	'content_path', "Mod/Db7c5fd/",
	'author', "Ablomis",
	'version_minor', 1,
	'version', 823,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/CTHCalc.lua",
		"Code/ChanceToHit.lua",
		"Code/DamageCalculation.lua",
		"Code/FirearmProperty.lua",
		"Code/GetAttackAPCost.lua",
		"Code/InventoryRolloverInfo.lua",
		"Code/MaxActionPoints.lua",
		"Code/RolloverInventoryWeaponBase.lua",
		"Code/AllAmmoCausesBleeding.lua",
		"InventoryItem/AK47.lua",
		"InventoryItem/AUG.lua",
		"InventoryItem/AR15.lua",
		"InventoryItem/AK74.lua",
		"InventoryItem/FAMAS.lua",
		"InventoryItem/FNFAL.lua",
		"InventoryItem/G36.lua",
		"InventoryItem/Galil.lua",
		"InventoryItem/M14SAW.lua",
		"InventoryItem/M16A2.lua",
		"InventoryItem/Gewehr98.lua",
		"InventoryItem/BarretM82.lua",
		"InventoryItem/DragunovSVD.lua",
		"InventoryItem/M24Sniper.lua",
		"InventoryItem/PSG1.lua",
		"InventoryItem/Winchester1894.lua",
		"InventoryItem/BrowningM2HMG.lua",
		"InventoryItem/FNMinimi.lua",
		"InventoryItem/HK21.lua",
		"InventoryItem/MG42.lua",
		"InventoryItem/RPK74.lua",
		"InventoryItem/AKSU.lua",
		"InventoryItem/M4Commando.lua",
		"InventoryItem/MP5.lua",
		"InventoryItem/MP5K.lua",
		"InventoryItem/UZI.lua",
		"InventoryItem/AA12.lua",
		"InventoryItem/Auto5.lua",
		"InventoryItem/DoubleBarrelShotgun.lua",
		"InventoryItem/M41.lua",
	},
	'saved', 1690243611,
	'code_hash', 7290841271150673948,
	'steam_id', "3008768068",
})