return PlaceObj('ModDef', {
	'title', "Revised",
	'description', "This mod is designed to create more complete experiencel, reflecting real life combat as much as possible.\nThe design philosophy of the mod: deadlier weapons, lower accuracy.\n\nNOT Vanilla save compatible.\n\nMajor changes:\n1. Auto damage increased\n2. Accuracy decreased to compensate.\n3. Dexterity used for close-range combat, marksmanship for aiming\n4. Lighting reflexes should not work on stealth kill\n5. Each weapon now has AP ready\n6. Increased number of AP for mercs to compensate\n7. All wounds cause bleeding if no armor or armor is penetrated\n8 Damage falloff beyond effective range\n9. Grenades are always inaccurate\n\nThis is ALPHA version of the mod - might be not well balanced. Feedback and suggestions are welcome.",
	'image', "Mod/Db7c5fd/Images/JA3Revised 2.png",
	'last_changes', "softlock fix?",
	'id', "Db7c5fd",
	'content_path', "Mod/Db7c5fd/",
	'author', "Ablomis",
	'version_minor', 1,
	'version', 1097,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/.44 Ammo.lua",
		"Code/5.45x39 Ammo.lua",
		"Code/50 BMGAmmo.lua",
		"Code/556 AMMO.lua",
		"Code/7.62x54R Ammo.lua",
		"Code/762 WP Ammo.lua",
		"Code/762NATO Ammo.lua",
		"Code/9mm AMMO.lua",
		"Code/AllAmmoCausesBleeding.lua",
		"Code/CTHCalc.lua",
		"Code/ChanceToHit.lua",
		"Code/ClassDef-Inventory.lua",
		"Code/CombatActionGrenade.lua",
		"Code/CombatActions.lua",
		"Code/DamageCalculation.lua",
		"Code/GetAttackAPCost.lua",
		"Code/InventoryRolloverInfo.lua",
		"Code/MaxActionPoints.lua",
		"Code/RolloverInventoryWeaponBase.lua",
		"Code/SniperSetup.lua",
		"InventoryItem/HiPower.lua",
		"InventoryItem/Bereta92.lua",
		"InventoryItem/Glock18.lua",
		"InventoryItem/ColtPeacemaker.lua",
		"InventoryItem/TexRevolver.lua",
		"InventoryItem/ColtAnaconda.lua",
		"InventoryItem/DesertEagle.lua",
		"InventoryItem/MP40.lua",
		"InventoryItem/UZI.lua",
		"InventoryItem/MP5.lua",
		"InventoryItem/MP5K.lua",
		"InventoryItem/AKSU.lua",
		"InventoryItem/M4Commando.lua",
		"InventoryItem/AK47.lua",
		"InventoryItem/AK74.lua",
		"InventoryItem/FAMAS.lua",
		"InventoryItem/AUG.lua",
		"InventoryItem/AR15.lua",
		"InventoryItem/M16A2.lua",
		"InventoryItem/G36.lua",
		"InventoryItem/FNFAL.lua",
		"InventoryItem/Galil.lua",
		"InventoryItem/M14SAW.lua",
		"InventoryItem/MG42.lua",
		"InventoryItem/FNMinimi.lua",
		"InventoryItem/HK21.lua",
		"InventoryItem/RPK74.lua",
		"InventoryItem/DoubleBarrelShotgun.lua",
		"InventoryItem/Auto5.lua",
		"InventoryItem/M41.lua",
		"InventoryItem/AA12.lua",
		"InventoryItem/BrowningM2HMG.lua",
		"InventoryItem/Winchester1894.lua",
		"InventoryItem/Gewehr98.lua",
		"InventoryItem/DragunovSVD.lua",
		"InventoryItem/M24Sniper.lua",
		"InventoryItem/PSG1.lua",
		"InventoryItem/BarretM82.lua",
	},
	'saved', 1690517722,
	'code_hash', 7349898165417887437,
	'steam_id', "3008768068",
})