-- ========== GENERATED BY AIArchetype Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('AIArchetype', {
	BaseAttackTargeting = set( "Torso" ),
	BaseMovementWeight = 10,
	Behaviors = {
		PlaceObj('StandardAI', {
			'BiasId', "Standard",
			'Weight', 150,
			'EndTurnPolicies', {
				PlaceObj('AIPolicyTakeCover', {
					'Weight', 50,
					'visibility_mode', "team",
				}),
				PlaceObj('AIPolicyDealDamage', nil),
			},
			'TakeCoverChance', 50,
		}),
	},
	Comment = "Keywords: Soldier, Sniper, Control, Ordnance, Smoke, Explosives",
	MoveStance = "Crouch",
	OptLocPolicies = {
		PlaceObj('AIPolicyTakeCover', {
			'Weight', 300,
		}),
		PlaceObj('AIPolicyHighGround', {
			'RequiredKeywords', {
				"Sniper",
			},
			'Weight', 200,
		}),
		PlaceObj('AIPolicyLosToEnemy', {
			'Weight', 300,
		}),
		PlaceObj('AIPolicyWeaponRange', {
			'Weight', 50,
			'RangeMin', 10,
			'RangeMax', 25,
		}),
		PlaceObj('AIPolicyWeaponRange', {
            'Weight', 50,
			'RangeMin', 26,
			'RangeMax', 49,
		}),
		PlaceObj('AIPolicyWeaponRange', {
			'Weight', 150,
			'RangeMin', 50,
			'RangeMax', 100,
		}),
	},
	OptLocSearchRadius = 80,
	PrefStance = "Crouch",
	SignatureActions = {
		PlaceObj('AIAttackSingleTarget', {
			'BiasId', "Autofire",
			'Weight', 150,
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "Autofire",
					'Effect', "disable",
					'Period', 0,
					'ApplyTo', "Team",
				}),
			},
			'NotificationText', "",
			'RequiredKeywords', {
				"Soldier",
			},
			'action_id', "AutoFire",
			'AttackTargeting', set( "Torso" ),
		}),
		PlaceObj('AIActionPinDown', {
			'BiasId', "PinDownAttack",
			'Weight', 80,
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "PinDownAttack",
					'Value', -50,
					'ApplyTo', "Team",
				}),
			},
			'RequiredKeywords', {
				"Sniper",
			},
		}),
		PlaceObj('AIActionThrowGrenade', {
			'BiasId', "AssaultGrenadeThrow",
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "AssaultGrenadeThrow",
					'Effect', "disable",
				}),
				PlaceObj('AIBiasModification', {
					'BiasId', "AssaultGrenadeThrow",
					'Effect', "disable",
					'Period', 0,
					'ApplyTo', "Team",
				}),
			},
			'RequiredKeywords', {
				"Explosives",
			},
			'self_score_mod', -1000,
		}),
		PlaceObj('AIActionThrowGrenade', {
			'BiasId', "SmokeGrenade",
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "SmokeGrenade",
					'Effect', "disable",
				}),
				PlaceObj('AIBiasModification', {
					'BiasId', "SmokeGrenade",
					'Effect', "disable",
					'Period', 0,
					'ApplyTo', "Team",
				}),
			},
			'RequiredKeywords', {
				"Smoke",
			},
			'enemy_score', 0,
			'team_score', 100,
			'self_score_mod', 100,
			'MinDist', 0,
			'SmokeGrenade', true,
		}),
		PlaceObj('AIActionHeavyWeaponAttack', {
			'BiasId', "LauncherFire",
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "LauncherFire",
					'Effect', "disable",
					'Period', 0,
				}),
				PlaceObj('AIBiasModification', {
					'BiasId', "LauncherFire",
					'Value', -50,
					'Period', 0,
					'ApplyTo', "Team",
				}),
			},
			'RequiredKeywords', {
				"Ordnance",
			},
			'self_score_mod', -1000,
			'MinDist', 5000,
			'LimitRange', true,
			'MaxTargetRange', 30,
		}),
		PlaceObj('AIActionHeavyWeaponAttack', {
			'BiasId', "RocketFire",
			'Weight', 200,
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "RocketFire",
					'Effect', "disable",
				}),
			},
			'RequiredKeywords', {
				"Ordnance",
			},
			'self_score_mod', -1000,
			'MinDist', 5000,
			'action_id', "RocketLauncherFire",
			'LimitRange', true,
			'MaxTargetRange', 30,
		}),
		PlaceObj('AIAttackSingleTarget', {
			'BiasId', "GroinShot",
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "GroinShot",
					'Effect', "disable",
					'Period', 0,
					'ApplyTo', "Team",
				}),
				PlaceObj('AIBiasModification', {
					'BiasId', "GroinShot",
					'Effect', "disable",
				}),
			},
			'RequiredKeywords', {
				"Sniper",
			},
			'Aiming', "Remaining AP",
			'AttackTargeting', set( "Groin" ),
		}),
		PlaceObj('AIConeAttack', {
			'BiasId', "Overwatch",
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "Overwatch",
					'Value', -50,
					'ApplyTo', "Team",
				}),
				PlaceObj('AIBiasModification', {
					'BiasId', "Overwatch",
					'Effect', "disable",
					'Value', -50,
					'Period', 2,
				}),
			},
			'RequiredKeywords', {
				"Soldier",
			},
			'team_score', 0,
			'min_score', 300,
			'action_id', "Overwatch",
		}),
		PlaceObj('AIConeAttack', {
			'BiasId', "SpamOverwatch",
			'Weight', 200,
			'OnActivationBiases', {
				PlaceObj('AIBiasModification', {
					'BiasId', "SpamOverwatch",
					'Effect', "disable",
					'Value', -50,
					'ApplyTo', "Team",
				}),
			},
			'RequiredKeywords', {
				"Control",
			},
			'team_score', 0,
			'min_score', 100,
			'action_id', "Overwatch",
		}),
	},
	TargetScoreRandomization = 10,
	group = "Simplified",
	id = "Soldier",
	save_in = "Libs/Network",
})

