const.Combat.AimCritBonus = 5
const.Combat.EnergyToDamageCoef =0.01663202
const.Combat.HeadCritChance = 95
const.Combat.LimbCritChance = 5
const.Combat.MinCritChance = 5
const.Combat.CriticalDamage = 60
const.Combat.MaxCritDistance = 5
const.Combat.ArmorDamageReductionBase = 5
const.Combat.ArmorDamageReductionAdditional = 45
const.Combat.ArmorDegradePercent = 10
const.Combat.UnconsciousMult = 4
const.Combat.UnconsciousDelay = 1
const.Combat.ExposedCoverCTHPenalty = -10
const.Combat.CrouchedCTHPenalty = -15
const.Combat.ProneCTHPenalty = -25
const.Combat.CoverCTHPenalty = -40
const.Combat.MoveModifier = 50