-- ========== GENERATED BY FXPreset Editor (Ctrl-Alt-F) DO NOT EDIT MANUALLY! ==========

PlaceObj('ActionFXInherit_Actor', {
	Actor = "PistolSuppressor",
	Comment = "For custom Silencer",
	Inherit = "Silencer",
	group = "Weapons VFX",
	id = "MJN43ers",
})

PlaceObj('ActionFXInherit_Actor', {
	Actor = "PistolImprovisedSuppressor",
	Comment = "For custom Silencer 2",
	Inherit = "Silencer",
	group = "Weapons VFX",
	id = "5BxWcYKs",
})

