UndefineClass('AR15')
DefineClass.AR15 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "AssaultRifle",
	Reliability = 80,
	ScrapParts = 10,
	Icon = "UI/Icons/Weapons/AR15",
	DisplayName = T(483958525407, --[[ModItemInventoryItemCompositeDef AR15 DisplayName]] "AR-15"),
	DisplayNamePlural = T(550683925295, --[[ModItemInventoryItemCompositeDef AR15 DisplayNamePlural]] "AR-15s"),
	Description = T(447539439478, --[[ModItemInventoryItemCompositeDef AR15 Description]] "Created to ensure the highest constitutional rights of self-defense and the possibility to bear a weapon that's easy as hell to convert to a fully-automatic one because a law-abiding citizen always needs one."),
	AdditionalHint = T(948350822906, --[[ModItemInventoryItemCompositeDef AR15 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Highly modifiable\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No Auto firing mode with standard Stock"),
	LargeItem = true,
	UnitStat = "Marksmanship",
	Cost = 1800,
	Caliber = "556",
	Platform = "AR15",
	Damage = 22,
	AimAccuracy = 4,
	BaseAccuracy = 92,
	CritChanceScaled = 30,
	MagazineSize = 30,
	PenetrationClass = 2,
	WeaponRange = 28,
	DamageFalloff = 75,
	Recoil = 22,
	OverwatchAngle = 1440,
	HandSlot = "TwoHanded",
	Entity = "Weapon_AR15",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"ScopeCOG",
				"LROptics",
				"LROpticsAdvanced",
				"ThermalScope",
				"ReflexSight",
				"DefaultIronsight_AR15",
				"ImprovedIronsight_AR15",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
				"BarrelLong",
				"BarrelLongImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy_AR_BurstOnly",
				"StockLight_AR_BurstOnly",
				"StockBump",
			},
			'DefaultComponent', "StockHeavy_AR_BurstOnly",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher",
				"VerticalGrip",
				"TacGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"ImprovisedSuppressor",
				"Suppressor",
				"MuzzleBooster",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 6000,
	ReloadAP = 3000,
	ReadyAP = 3000,
}

